stronka/monitoring/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.dev_table, name='dev_table'),
    url(r'^config', views.configuration, name='config'),
    url(r'cron', views.cron, name='cron'),
    url(r'^ping_history_list/$', views.ping_history_list),
    url(r'^ping_history_list/(?P<pk>[0-9]+)/$', views.ping_history_list_device),
]

stronka/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('monitoring.urls')),
]

stronka/monitoring/models.py
from django.db import models
from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles

LEXERS = [item for item in get_all_lexers() if item[1]]
LANGUAGE_CHOICES = sorted([(item[1][0], item[0]) for item in LEXERS])
STYLE_CHOICES = sorted((item, item) for item in get_all_styles())


class Device(models.Model):
    ip = models.CharField(max_length = 100, null=True, blank=True)
    login = models.CharField(max_length = 100, null=True, blank=True)
    password = models.CharField(max_length = 100, null=True, blank=True)
    port = models.IntegerField(null=True, blank=True)
    status = models.CharField(max_length = 100, null=True, blank=True)
    dev_name = models.CharField(max_length = 100, null=True, blank=True)
    firmware = models.CharField(max_length = 100, null=True, blank=True)
    wireless_mode = models.CharField(max_length = 100, null=True, blank=True)
    ssid = models.CharField(max_length = 100, null=True, blank=True)
    signal = models.IntegerField(null=True, blank=True)
    ccq = models.IntegerField(null=True, blank=True)
    air_q =models.IntegerField(null=True, blank=True)
    air_c = models.IntegerField(null=True, blank=True)
    freq = models.IntegerField(null=True, blank=True)
    uptime = models.CharField(max_length = 100, null=True, blank=True)
    product = models.CharField(max_length = 100, null=True, blank=True)
    last_seen = models.CharField(max_length = 100, null=True, blank=True)
    ping = models.IntegerField(null=True, blank=True)
    error = models.CharField(max_length = 100, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.ip

class Ping_history(models.Model):
    device = models.ForeignKey(Device)
    avg = models.CharField(max_length = 100, null=True, blank=True)
    date = models.CharField(max_length = 100, null=True, blank=True)
    
    def publish(self):
        self.save()

class Cron(models.Model):
    monitor_minutes = models.IntegerField(null=True, blank=True)
    ping_check = models.IntegerField(null=True, blank=True)
    backup_days = models.IntegerField(null=True, blank=True)

    def publish(self):
        self.save()

class Mail(models.Model):
    mail_to = models.CharField(max_length = 100, null=True, blank=True)

    def publish(self):
        self.save()

stronka/monitoring/forms.py
from django import forms

class ConfigForm(forms.Form):
    ip = forms.CharField(max_length=100)
    login = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput)
    port = forms.CharField(max_length=100)

    def __init__(self, *args, **kwargs):
        super(ConfigForm, self).__init__(*args, **kwargs)
        self.fields['ip'].label = "adres sieci"
        self.fields['login'].label = "domyślny login"
        self.fields['password'].label = 'domyślne hasło'
        self.fields['port'].label = "port SSH"

class CronForm(forms.Form):
    monitor_minutes = forms.CharField(max_length=100)
    ping_check = forms.CharField(max_length=100)
    backup_days = forms.CharField(max_length=100)

    def __init__(self, *args, **kwargs):
        super(CronForm, self).__init__(*args, **kwargs)
        self.fields['monitor_minutes'].label = "czas monitorowania"
        self.fields['ping_check'].label = "czas pingowania"
        self.fields['backup_days'].label = "dni backupu"

class MailForm(forms.Form):
    mail_to = forms.CharField(max_length=100)

stronka/monitoring/views.py
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from rest_framework.renderers import JSONRenderer
from .serializers import Ping_historySerializer
from .models import Ping_history
from django.db import connection
from crontab import CronTab
from .models import Device
from django.shortcuts import render
from django_tables2 import RequestConfig
from .tables import DevicesTable
from .forms import ConfigForm
from .forms import CronForm, MailForm
from .lib.discover import ubnt_discovery
from .lib.ping import ping
from .lib.update import update
#from .lib.monitor import monitor
from .lib.db_connector import siema
import sqlite3
import subprocess
import os



@csrf_exempt
def ping_history_list(request):
    """
    List all code snippets, or create a new snippet.
    """
    if request.method == 'GET':
        history = Ping_history.objects.all()
        serializer = Ping_historySerializer(history, many=True)
        return JsonResponse(serializer.data, safe=False)

@csrf_exempt
def ping_history_list_device(request, pk):
    """
    Retrieve, update or delete a code snippet.
    """
    try:
        history = Ping_history.objects.all().filter(device=pk)
    except Ping_history.DoesNotExist:
        return HttpResponse(status=404)

    if request.method == 'GET':
        serializer = Ping_historySerializer(history, many=True)
        return JsonResponse(serializer.data, safe=False)

@login_required
def dev_table(request):
    if request.POST.get("Update"):
        update(request.POST.getlist('cBox[]'))
        return HttpResponseRedirect('/')
    if request.POST.get("check"):
        ping()
        return HttpResponseRedirect('/')
    else:
        table = DevicesTable(Device.objects.all())
        RequestConfig(request).configure(table)
        table.paginate(page=request.GET.get('page', 1), per_page=500)
        return render(request, 'monitoring/device_list.html', {'table': table})

@login_required
def configuration(request):
    if request.method == 'POST':
        form = ConfigForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            ubnt_discovery(data)
            return HttpResponseRedirect('/')
    else:
        form = ConfigForm()

    return render(request, 'monitoring/config.html', {'form': form})

@login_required
def cron(request):
    if request.method == 'POST':
        cron_form = CronForm(request.POST)
        if cron_form.is_valid():
            data = cron_form.cleaned_data
            print(data)
            users_cron = CronTab(user='karol')
            users_cron.remove_all()

            monit_job = users_cron.new(command='/usr/bin/python3 %s/monitoring/lib/monitor.py' %(os.getcwd()), )
            monit_job.minute.every(data['monitor_minutes'])

            ping_job = users_cron.new(command='/usr/bin/python3 %s/monitoring/lib/ping.py' %(os.getcwd()), )
            ping_job.minute.every(data['ping_check'])

            backup_job = users_cron.new(command='/usr/bin/python3 %s/monitoring/lib/backup.py' %(os.getcwd()), )
            backup_job.day.every(data['backup_days'])

            users_cron.write()
            return HttpResponseRedirect('/')
    else:
        form = CronForm()

    return render(request, 'monitoring/cron.html', {'form': form})

stronka/monitoring/templates/monitoring/config.html
{% load staticfiles %}
{% load static %}
<html>
    <head>
        <title>monitoring</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/monitoring.css' %}">
<style>
 

    label[for='id_ip'] {
        
        padding-right: 33px;
    }
    label[for='id_login'] {
       
        padding-right: 3px;
    }
    label[for='id_port'] {
        
        padding-right: 45px;
    }
    input {
                padding: 5px;
                border: solid 5px #c9c9c9;
                
                transition: box-shadow 0.3s, border 0.3s;
            }

            input:focus {
                border: solid 5px #969696;
            }
    </style>


    </head>
    <body>
        <div>
            <h1>Podaj parametry skanowania</h1>
        </div>
<form action="" method="post">
{% csrf_token %}

<ul class="contactList">
       {{ form.as_p }}
    </ul>
<input type="submit" name="newsletter_sub" value="Scan" />
</form>
    </body>
</html>

stronka/monitoring/templates/monitoring/cron.html
{% load staticfiles %}
{% load static %}
<html>
    <head>
        <title>monitoring</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/monitoring.css' %}">

        <style>
        

    label[for='id_monitor_minutes'] {
        
          }
    label[for='id_ping_check'] {
       
        padding-right: 21px;
    }
    label[for='id_backup_days'] {
        
        padding-right: 48px;
    }
    input {
                padding: 5px;
                border: solid 5px #c9c9c9;
                
                transition: box-shadow 0.3s, border 0.3s;
            }

            input:focus {
                border: solid 5px #969696;
            }


        </style>

    </head>
    <body>
        <div>
            <h1>Cron config</h1>
        </div>
<form action="" method="post">
{{ form.as_p }}
{% csrf_token %}
<input type="submit" onclick="alert('Zrobione!')" name="newsletter_sub" value="update"/>
</form>
    </body>
</html>

stronka/monitoring/templates/monitoring/device_list.html
{% load staticfiles %}
{% load render_table from django_tables2 %}
{% load static %}
<html>
    <head>
        <title>monitoring</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/monitoring.css' %}">
        <link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" />

        <style>
          body {
             background-color: #417690;
          }
          h1 {
              color: white;
          }
            .link:link, .link:visited {

                background-color: #999999;
                color: white;
                padding: 14px 25px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
            }

            .link:hover, .link:active {
                background-color: #003d4d;
            }

            html {
                text-align: left;
            }

            input {
                padding: 5px;
                border: solid 5px #c9c9c9;
                
                transition: box-shadow 0.3s, border 0.3s;
            }

            input:focus {
                border: solid 5px #969696;
            }
            #tabelka {
                padding-top: 5px;
            }
            #submity {
                padding-top: 5px;
            }

        </style>
        <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>


<script>

var jsonik = [];
var counter;

var series1 = { //dataSeries - first quarter
                type: "column",
                name: "Latency",
                showInLegend: true
            };

$(document).ready(function(){

    $(".ip").hover(function(){

        //alert($(this).prev().text());
        $.getJSON('http://127.0.0.1:8000/ping_history_list/50/', {
    tags: "avg",
    tagmode: "any",
    format: "json"
  }, function(result){
      counter = result.length;
      jsonik = result;
            });

            var color = CanvasJS.addColorSet("greenShades",
                [//colorSet Array

                "#2F4F4F",               
                ]);

            var chart = new CanvasJS.Chart("chartContainer");

        
            chart.options.axisY = { suffix: " ms" };
            chart.options.title = { text: "Ping" };
        
            chart.options.data = [];
            chart.options.data.push(series1);

            series1.dataPoints = [
                    { label: jsonik[counter-10].date, y: parseFloat(jsonik[counter-10].avg) },
                    { label: jsonik[counter-9].date, y: parseFloat(jsonik[counter-9].avg) },
                    { label: jsonik[counter-8].date, y: parseFloat(jsonik[counter-8].avg) },
                    { label: jsonik[counter-7].date, y: parseFloat(jsonik[counter-7].avg) },
                    { label: jsonik[counter-6].date, y: parseFloat(jsonik[counter-6].avg) },
                    { label: jsonik[counter-5].date, y: parseFloat(jsonik[counter-5].avg) },
                    { label: jsonik[counter-4].date, y: parseFloat(jsonik[counter-4].avg) },
                    { label: jsonik[counter-3].date, y: parseFloat(jsonik[counter-3].avg) },
                    { label: jsonik[counter-2].date, y: parseFloat(jsonik[counter-2].avg) },
                    { label: jsonik[counter-1].date, y: parseFloat(jsonik[counter-1].avg) }
            ];
        
            chart.render();

    });
    $(".id").hide();
        });

        
    </script>


    </head>
    <body>
        <div>
            <h1>Monitoring</h1>
        </div>
    <a class="link" href="/config/">Scan</a>
    <a class="link" href="/cron/">Cron Config</a>
    <a class="link" href="/admin/">Admin</a>
    <a class="link" href="/admin/logout/">LOG OUT</a>
    <form action="/" method="post">
    <div id="submity">
        <input type="submit" name="check" value="Check status" />
        <input type="submit" name="monitor" value="Monitor" /> 
        <input type="submit" name="Update" value="Update" /> 
    </div>
    <div id="tabelka">
        {% csrf_token %}
        {% render_table table %}
    </div>
        </form>
<div id="chartContainer" style="height: 300px; width: 50%;"></div>
    </body>
</html>